#!/bin/bash

date +"%T"

#for line in $(ls /home/m/mulhemp/sift/train/*.sift); do

#name=$( basename $line )

#./script_clean_sift $name

#done

for line in $(ls /home/m/mulhemp/sift/train/*.sift); do

name=$( basename $line )

./script_clean_sift $name

done

date +"%T"
